### ISSUE TITLE
Token parameter in the API

### ISSUE THREAD

**Issue by gvsrini** [andrei-m-code/net-core-push-notifications#13]
How do I get the token. It seems to be ambiguously named as device id. If you can give an example of retrieving the token before invoking the API, that would be of great help.

**Comment by andrei-m-code** [comment]
@gvsrini I'm assuming you're looking to implement push notification for Android and/or iOS mobile applications. Here is official documentation links:

https://developer.apple.com/documentation/usernotifications/registering_your_app_with_apns
https://firebase.google.com/docs/cloud-messaging/android/client

Hope this helps.
