### ISSUE TITLE
Can i use your code in a commercial project ?

### ISSUE THREAD

**Issue by tvxuan4** [andrei-m-code/net-core-push-notifications#14]
Hi, 
We want to use your module for one project. Can you tell us what the license is?
Can you add a open source license
Thanks,
Xuan

**Comment by andrei-m-code** [comment]
Yes it can be used for commercial projects. I'll add license info in a bit. Optionally you can PR license details and I'll accept.

**Comment by andrei-m-code** [comment]
@tvxuan4 the MIT license record is added. Please feel free to use the library. Thank you!
