### ISSUE TITLE
Issue with updating to 2.1.1

### ISSUE THREAD

**Issue by pvhd** [andrei-m-code/net-core-push-notifications#18]
I was trying to update the package to the latest version, but received this error: "Could not install package 'CorePush 2.1.1'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.7.2', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author." 

Could you please help? Thank you.

**Comment by andrei-m-code** [comment]
@pvhd it seems like you're trying to use this package from .NET Framework 4.7.2. Unfortunately this package can only be used by apps targeting .NET Core 3.1 and above.
