### ISSUE TITLE
Issue when calling SendAsync for apn

### ISSUE THREAD

**Issue by pvhd** [andrei-m-code/net-core-push-notifications#19]
When using apn.SendAsync, I got this error: Error 12175 calling WINHTTP_CALLBACK_STATUS_REQUEST_ERROR, 'A security error occurred'. Could you please help? Thank you.

**Comment by andrei-m-code** [comment]
@pvhd what version of .NET do you use? What operating system?

**Comment by pvhd** [comment]
I use .Net framework 4.8

**Comment by andrei-m-code** [comment]
@pvhd sorry buddy, you're out of luck. This lib is for .NET Core 3.1+, you can try earlier versions and see if they work for you, but the latest one is for LTS 3.1 and above.
