### ISSUE TITLE
Voip push is not supporting.

### ISSUE THREAD

**Issue by anjandaffo** [andrei-m-code/net-core-push-notifications#21]
Kindly provide the option of apns-push-type in sendAsync method. This way we can pass the apns-push-type to "voip" for voip push. This need to be sent in header of request.

**Comment by andrei-m-code** [comment]
@anjandaffo is this a part of notification payload? If so you can add it yourself? The notification payload can be any data class, I only serialize it into json before sending to apn server.

**Comment by VictorK1902** [comment]
Why is this closed? 

The following changes have to be made in order for voip to work according to apple latest documentation:

[https://developer.apple.com/documentation/usernotifications/setting_up_a_remote_notification_server/sending_notification_requests_to_apns/]


    enum ApnsPushType {Alert, Background, VoIP, Complication, FileProvider, MDM}

    public async Task<ApnsResponse> SendAsync(
                object notification,
                string deviceToken,
                string apnsId = null,
                int apnsExpiration = 0,
                int apnsPriority = 10,
                ApnsPushType pushType = ApnsPushType.Alert,
                string mdmUID = "")
    {
        var path = $"/3/device/{deviceToken}";
        var json = JsonHelper.Serialize(notification);

        var request = new HttpRequestMessage(HttpMethod.Post, new Uri(servers[server] + path))
        {
            Version = new Version(2, 0),
            Content = new StringContent(json)
        };

        switch (pushType){
            case ApnsPushType.VoIP: appBundleIdentifier += ".voip"; break;
            case ApnsPushType.Complication: appBundleIdentifier += ".complication"; break;
            case ApnsPushType.FileProvider: appBundleIdentifier += ".pushkit.fileprovider"; break;
        }

        request.Headers.Authorization = new System.Net.Http.Headers.AuthenticationHeaderValue("bearer", jwtToken.Value);
        request.Headers.TryAddWithoutValidation(":method", "POST");
        request.Headers.TryAddWithoutValidation(":path", path);
        if (pushType == ApnsPushType.MDM)
            request.Headers.Add("apns-topic", mdmUID);
        else
            request.Headers.Add("apns-topic", appBundleIdentifier);
        request.Headers.Add("apns-expiration", apnsExpiration.ToString());
        request.Headers.Add("apns-priority", apnsPriority.ToString());
        request.Headers.Add("apns-push-type", pushType.ToString().ToLower(); // for iOS 13 required
        if (!string.IsNullOrWhiteSpace(apnsId))
        {
            request.Headers.Add(apnidHeader, apnsId);
        }

        using var response = await http.Value.SendAsync(request);
        var succeed = response.IsSuccessStatusCode;
        var content = await response.Content.ReadAsStringAsync();
        var error = JsonHelper.Deserialize<ApnsError>(content);

        return new ApnsResponse
        {
            IsSuccess = succeed,
            Error = error
        };
    }
