### ISSUE TITLE
Token refresh time?

### ISSUE THREAD

**Issue by Appelg** [andrei-m-code/net-core-push-notifications#22]
https://developer.apple.com/documentation/usernotifications/setting_up_a_remote_notification_server/establishing_a_token-based_connection_to_apns

The documentation says:

> For security, APNs requires you to refresh your token regularly. **Refresh your token no more than once every 20 minutes** and no less than once every 60 minutes. APNs rejects any request whose token contains a timestamp that is more than one hour old. Similarly, **APNs reports an error if you recreate your tokens more than once every 20 minutes.**

I'm reading the code but I cannot see how this is handled.

I guess we need do to something like:
Store the token in a static object after the first instantiation of ApnSender, then provide this saved token next time, and recreate the token if older than 60 mins...

It would also be nice to be able to:
- provide a token as input
- fetch the current generated token
- expose the token generator as a helper

This since I guess I need to use the same token for all concurrent running applications in order to obey the "no more then 20 minutes" rule....

**Comment by andrei-m-code** [comment]
@Appelg it depends on how your application is designed. Current implementation is good for sending a set of messages and disposing sender when done. Got more messages to send? Create a new ApnSender instance with the new token. However you brought up a good point. Ideally we should be checking if token is too old and if so, re-create it inside the sender every 20mins. I'll definitely look into it.

**Comment by airobot60** [comment]
> https://developer.apple.com/documentation/usernotifications/setting_up_a_remote_notification_server/establishing_a_token-based_connection_to_apns
> 
> 
> 
> The documentation says:
> 
> 
> 
> > For security, APNs requires you to refresh your token regularly. **Refresh your token no more than once every 20 minutes** and no less than once every 60 minutes. APNs rejects any request whose token contains a timestamp that is more than one hour old. Similarly, **APNs reports an error if you recreate your tokens more than once every 20 minutes.**
> 
> 
> 
> I'm reading the code but I cannot see how this is handled.
> 
> 
> 
> I guess we need do to something like:
> 
> Store the token in a static object after the first instantiation of ApnSender, then provide this saved token next time, and recreate the token if older than 60 mins...
> 
> 
> 
> It would also be nice to be able to:
> 
> - provide a token as input
> 
> - fetch the current generated token
> 
> - expose the token generator as a helper
> 
> 
> 
> This since I guess I need to use the same token for all concurrent running applications in order to obey the "no more then 20 minutes" rule....

**Comment by andrei-m-code** [comment]
@Appelg I believe v3.0.0 addresses your concerns. Thanks for your feedback.
