### ISSUE TITLE
Make more testable

### ISSUE THREAD

**Issue by neiesc** [andrei-m-code/net-core-push-notifications#23]
Could we create an interface for ApnSender?

**Comment by andrei-m-code** [comment]
@neiesc absolutely. Great idea.

**Comment by neiesc** [comment]
You may need it for other methods too, but for now, I'm going to do ApnSender.

**Comment by andrei-m-code** [comment]
@neiesc I just released a new version 2.1.2 it should be available on nuget within an hour or so I think. Thanks for your feedback
