### ISSUE TITLE
Allow injecting HttpClient

### ISSUE THREAD

**Issue by Dreamescaper** [andrei-m-code/net-core-push-notifications#24]
I see that suggested approach is to create and dispose sender for each batch. However, each sender creates separate HttpClient, which is a bad thing, as might lead to sockets starvation.
I would like to inject my own instance of HttpClient created via HttpClientFactory (see [here](https://docs.microsoft.com/ru-ru/dotnet/architecture/microservices/implement-resilient-applications/use-httpclientfactory-to-implement-resilient-http-requests)) to avoid this issue.

**Comment by VictorK1902** [comment]
I looked into the Send logic and saw that too. Eventually I ended up making a few minor changes, including this, and use that instead. The whole library is fairly simple as well so I manually installed the dependencies and extracting pieces that I need.

**Comment by andrei-m-code** [comment]
@Dreamescaper @VictorK1902 I understand that it is recommended to use HttpClientFactory and I'd gladly add it to the library. My only concern is it will make the library a bit harder to use. Some people wouldn't know how to deal with HttpClientFactory. I'll consider adding it in the future version however using the factory is not that critical anymore. Please see this blogpost https://www.stevejgordon.co.uk/httpclient-connection-pooling-in-dotnet-core.

Anyways, thanks for this great feedback!

**Comment by Dreamescaper** [comment]
My suggestion is not to use HttpClientFactory directly, but having HttpClient parameter in constructor (maybe as non-required parameter or as separate constructor to preserve backward compatibility).

Still, thanks for info about HttpClient, didn't know that.

**Comment by Dreamescaper** [comment]
Another reason for doing that - I'd like to be able to add custom HttpMessageHandler to be able to log requests/responses.

**Comment by andrei-m-code** [comment]
@Dreamescaper @VictorK1902 In v3.0.0 injecting HttpClient is mandatory. There are a few cases when some manipulations with http client are needed, like here https://github.com/andrei-m-code/net-core-push-notifications/pull/27. So to avoid it all together we now have it in constructor parameters. It also eliminates the need of IDisposable interface implementation. Makes it cleaner.

Thanks for your feedback.
