### ISSUE TITLE
problems after upgrade to 3.0

### ISSUE THREAD

**Issue by 78fede78** [andrei-m-code/net-core-push-notifications#28]
Hello in the documentation I read that the constructor that previously accepted two strings is now:

`var fcm = new FcmSender (settings, httpClient);`

it is not clear to me how these objects should be initialized

Old Code:

```
using (var fcm = new FcmSender(config["ServerKey"], config["SenderId"]))
{
	await fcm.SendAsync(deviceId, notification);
}
```

New Code:

```
FcmSettings sett = new FcmSettings();
sett.SenderId = config["SenderId"];
sett.SenderId = config["ServerKey"];
FcmSender fcm = new FcmSender(sett, new System.Net.Http.HttpClient());
```
I don't know if that's correct.
The using clause cannot be used because the object is not disposable.
What is the httpclient object for and how should it be instantiated?

**Comment by andrei-m-code** [comment]
@78fede78  This is all correct. One thing that you might want to do is wrap your HttpClient with `using` statement e.g.
```
using var http = new HttpClient();
var fcm = new FcmSender(settings, http);
await fcm.SendAsync(deviceId, notification);
```
