### ISSUE TITLE
Getting blank API response when i uninstall app from device and sent notification in same device

### ISSUE THREAD

**Issue by Trushal0066** [andrei-m-code/net-core-push-notifications#30]
Hello,

I am getting blank response from API when i uninstall app from device and try to sent notification in same device.
Is there anything implemented in same library for feedback service to delete device token which are not used. How can we do that

![image](https://user-images.githubusercontent.com/71371411/93302081-03ce2800-f817-11ea-9d34-e873b8fb984c.png)

**Comment by andrei-m-code** [comment]
@Trushal0066 this is really weird. Can you check response http status? What is it?

**Comment by Trushal0066** [comment]
@andrei-m-code 
It’s 200 status code return

**Comment by andrei-m-code** [comment]
I'm going to close it as no one else reported the issue. Might be something with your local/cloud environment...
