### ISSUE TITLE
Can use p12 instead of p8 in net-core-push-notifications?

### ISSUE THREAD

**Issue by neiesc** [andrei-m-code/net-core-push-notifications#33]
Can use p12 instead of p8 in net-core-push-notifications?

**Comment by andrei-m-code** [comment]
@neiesc the initial implementation used p12 certs. But I moved away from it, there was some reason, I just can't recall. Maybe it doesn't work with apple's new http/2? not sure. Anyway.. we don't support it, but feel free to contribute, maybe it would be a good addition.

**Comment by neiesc** [comment]
Our client currently uses p12 I already proposed p8 he didn't say anything so I'll leave it on standby

**Comment by andrei-m-code** [comment]
@neiesc gotcha. Maybe in the future.. For now most people seem to be content with p8.
