### ISSUE TITLE
3.0.1 fails to import certificate on Windows shared tier

### ISSUE THREAD

**Issue by Dreamescaper** [andrei-m-code/net-core-push-notifications#34]
`ImportPkcs8PrivateKey` requires the user profile be loaded, which is not true on shared tier (in Azure or other services) - it fails with an exception.

See the following issue for details:
https://github.com/aspnet-contrib/AspNet.Security.OAuth.Providers/issues/358

(It works as expected on previous versions)

**Comment by andrei-m-code** [comment]
@Dreamescaper  Are you getting it in Azure Function or Azure Web app?

**Comment by Dreamescaper** [comment]
@andrei-m-code 
It does not not work for the cheapest shared tier - you can't load profile there.

**Comment by andrei-m-code** [comment]
Limitations of the environment... 🤷‍♂️. Sorry buddy, I wish I could help you with it.

**Comment by Dreamescaper** [comment]
@andrei-m-code 
Windows.

Thing is that is works fine with 3.0.0 and BouncyCastle implementation.
If you don't like the idea of this external dependency, would be great to have ability to inject custom implementation (so in my case I'd inject that removed BouncyCastle implementation).

**Comment by andrei-m-code** [comment]
@Dreamescaper wow really? That's not good. I indeed hate to have that extra dependency, but if it doesn't work otherwise.. maybe injecting is an option. It certainly complicates things for average user though. I'll need to think about it.

**Comment by cuepack** [comment]
Hi Folks

We where facing a similar issue with on an hosted environment first. It turns out, that our hoster had an issue on a shared tier but was not able to fix it, therefore we moved our push notification service to a dedicated server (Windows 2019 with IIS). 

Initially it was not working there also, but after some investigations and trying if it is working with kestrel, it turns out - with kestrel it was working fine.

Then we focused again the application pool from the iis and switched the app pool identity from ApplicationPoolIdentity to NetworkService, after that push notification where send also using iis.

Maybe you can give it a try, hopefully it works for you too.

Best regards

cue

**Comment by romaromaniv** [comment]
Hi, Andrei,

have the same exception on my hosting environment.

Stack trace is

StackTrace:    at System.Security.Cryptography.CngKeyLite.ImportKeyBlob(String blobType, ReadOnlySpan`1 keyBlob, Boolean encrypted, ReadOnlySpan`1 password)
   at System.Security.Cryptography.CngPkcs8.ImportPkcs8(ReadOnlySpan`1 keyBlob)
   at System.Security.Cryptography.CngPkcs8.ImportPkcs8PrivateKey(ReadOnlySpan`1 source, Int32& bytesRead)
   at System.Security.Cryptography.ECDsaImplementation.ECDsaCng.ImportPkcs8PrivateKey(ReadOnlySpan`1 source, Int32& bytesRead)
   at CorePush.Apple.ApnSender.CreateJwtToken()
   at CorePush.Apple.ApnSender.<GetJwtToken>b__8_0(String _)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at CorePush.Apple.ApnSender.GetJwtToken()
   at CorePush.Apple.ApnSender.SendAsync(Object notification, String deviceToken, String apnsId, Int32 apnsExpiration, Int32 apnsPriority, Boolean isBackground)
   at BusinessLogic.Services.MobileNotificationService.SendMessage(String message, Int32 userId) in C:\Users\

**Comment by andrei-m-code** [comment]
Please use version 3.0.0. I'll revert the 3.0.1 changes when I release a new version. Thank you!

**Comment by romaromaniv** [comment]
Greate, 3.0.0 works as expected. Thank you!

**Comment by andrei-m-code** [comment]
v3.0.2 should now work for shared environments and whatnot
