### ISSUE TITLE
Usage of Windows Cryptography Next Generation

### ISSUE THREAD

**Issue by eimantas** [andrei-m-code/net-core-push-notifications#4]
I'm developing an ASP.NET API on macOS and I'm running it on Linux. When trying to push a notification I'm receiving an exception that WinCNG is not supported.

Is there a way I can work around this somehow?

**Comment by andrei-m-code** [comment]
@eimantas which version of the package do you use?

**Comment by eimantas** [comment]
It's 2.0.1 from nuget.org

**Comment by andrei-m-code** [comment]
@eimantas yes apparently I still have `CngKey.Import` call for Apple sender. Not exactly sure how to get rid of it atm.

**Comment by andrei-m-code** [comment]
@eimantas I asked a question on stackoverflow. Let's see if we get some help on this https://stackoverflow.com/questions/58856658/cngkey-import-fails-on-linux-and-macos

**Comment by eimantas** [comment]
Thanks for your efforst! Have an upvote ;)

**Comment by andrei-m-code** [comment]
@eimantas I've just released version 2.1.0 targeting netstandard2.1 with new cryptography and without WinHttpHandler. It should be working on Mac and Linux now. Would you be able to test it?
