### ISSUE TITLE
Can use in ApnSender metod SendAsync CancellationToken

### ISSUE THREAD

**Issue by neiesc** [andrei-m-code/net-core-push-notifications#40]
https://github.com/andrei-m-code/net-core-push-notifications/blob/master/CorePush/Apple/ApnSender.cs#L49
Can use CancellationToken?

**Comment by andrei-m-code** [comment]
Excellent point! We absolutely should! I'll add it with the next release

**Comment by neiesc** [comment]
Awesome is because we are implemented in a critical client that will be used in more than 120,000 notifications or more for about 8 countries.

**Comment by andrei-m-code** [comment]
This is still pending, but I really want to get it done. I'll see if I can get to it this weekend.

**Comment by neiesc** [comment]
No problem Andrei, thanks.

**Comment by andrei-m-code** [comment]
@neiesc v3.0.3 now have cancellation tokens in SendAsync signatures!
