### ISSUE TITLE
Improvements to Apple JWT token - via an interface

### ISSUE THREAD

**Issue by devology-rob** [andrei-m-code/net-core-push-notifications#41]
I can't use the current implementation of refreshing the JWT tokens because

a) I'm implementing an Azure function and this could scale up, each having their own isolated in-memory JWT tokens

b) The JWT tokens can be revoked at any time, so if there's a 403 response they should be cleared and re-attempted much earlier than their planned expiry

I have a fork where I'm hoping to contribute back to your plugin, but I've never done this before, so I'm submitting this issue in the hope I can attach the changes to it afterwards.

**Comment by andrei-m-code** [comment]
interesting point. @danielgindi was working on JWT token provider via the interface basically giving users freedom of managing tokens the way they want. We should all look more closely into it and get it into the main code base.

https://github.com/andrei-m-code/net-core-push-notifications/pull/43

**Comment by danielgindi** [comment]
Yes I already have a PR for caching the key itself. This will make it consume less resources each time regenerating the JWT.
You could base your work on it
