### ISSUE TITLE
Is it possible to revert to .NET Standard 2.0?

### ISSUE THREAD

**Issue by danielgindi** [andrei-m-code/net-core-push-notifications#44]
As .NET Standard 2.1 currently removes support for .NET Framework completely.

https://devblogs.microsoft.com/dotnet/announcing-net-standard-2-1/

States:
> In fact, most libraries should be able to stay on .NET Standard 2.0, as the API additions are largely for advanced scenarios

**Comment by andrei-m-code** [comment]
Yes, done! Thanks to you ;)
