### ISSUE TITLE
A task was cancelled

### ISSUE THREAD

**Issue by tonyfonager** [andrei-m-code/net-core-push-notifications#5]
When I try to use your library on a Windows project, I get this error message "A task was cancelled" when it try to reach the Apple APNS (Development) servers.

I do not know how to proceed from here ....

![image](https://user-images.githubusercontent.com/837894/68944252-b8d62500-07ad-11ea-9525-47b408ef86a4.png)

**Comment by andrei-m-code** [comment]
@tonyfonager would you be able to post more of your code as it's hard to see what's wrong from what we have now.

**Comment by tonyfonager** [comment]
I am just calling it just as in your example code, but with my own parameters.

**Comment by andrei-m-code** [comment]
@tonyfonager I need some details, unfortunately I can't guess why it's failing for you.

**Comment by tonyfonager** [comment]
I can understand, but only thing that differs from you example, is my parameters (TeamId, Bundle, private key etc), and you cannot use them for anything.

I just wanted to hear if the error made sense to you, if not - I guess I will move on ;-)

Thanks!

**Comment by andrei-m-code** [comment]
@tonyfonager all I can suggest, triple-check all parameters, make sure cert string has no `-----BEGIN CER..-----`  and what not, make sure all calls are awaited in your code, check the payload, know which server to send your message to e.g. Development/Production.

**Comment by andrei-m-code** [comment]
@tonyfonager seems like some parts of the library require .NET Core 3.1. So depending on your project it may or may not work. Thanks
