### ISSUE TITLE
Apple Push Notification service server certificate update

### ISSUE THREAD

**Issue by pvhd** [andrei-m-code/net-core-push-notifications#51]
Hello, I just received an email from Apple asking about updating the certificate. Do we need to do anything to accommodate this change when using this nuget package? Thanks.

Below is the email:

On March 29, 2021, token and certificate-based HTTP/2 connections to the Apple Push Notification service must incorporate the new root certificate (AAACertificateServices 5/12/2020) which replaces the old GeoTrust Global CA root certificate. To ensure a seamless transition and to avoid push notification delivery failures, verify that both the old and new root certificates for the HTTP/2 interface are included in the Trust Store of each of your notification servers before March 29.

Note that Apple Push Notification service SSL provider certificates issued to you by Apple do not need be to updated at this time.

**Comment by MakcStudio** [comment]
Hi, please tell me. On my mac, everything works, but as soon as I upload a project to linux with SendAsync, I get an exception:
"The SSL connection could not be established, see inner exception."
Have you ever encountered such a thing? And a few weeks ago everything worked exactly

**Comment by MakcStudio** [comment]
i fixed it

var httpClientHandler = new HttpClientHandler
            {
                // Return `true` to allow certificates that are untrusted/invalid
                ServerCertificateCustomValidationCallback =
              HttpClientHandler.DangerousAcceptAnyServerCertificateValidator
            };
            var httpClient = new HttpClient(httpClientHandler);

**Comment by andrei-m-code** [comment]
Yes, I think @MakcStudio solution should work. It's one of the reasons why we made http client injectable - to make sure users have flexibility of customizing communication settings like this.

**Comment by devology-rob** [comment]
Hi, 

On Linux, you'll probably have to install the AAACertificate certificate or put it somewhere where the operating system is expecting it.

In case anyone is using Azure Functions I've found that you can upload the [AAA Certificate Services Root (2028)](https://support.sectigo.com/Com_KnowledgeDetailPage?Id=kA03l00000117cL) within the Azure portal via the following menu

```
Home > App Services > Your-function > TLS / SSL > Public Key Certificates (.cer)
```

Once I performed the above your plugin automatically picked this SSL certificate up without any code tweaks needed.  I didn't even need to reboot the server, however, I branched the plugin to detect invalid JTW tokens during a push attempt then force a new JWT refresh.  If you're relying on refreshing it every 50 minutes then you may need to restart your function application.

Given the old GeoTrust Global CA root certificate is terminating around March 29th then installing the new AAACertificate above means you shouldn't need to change it until 2028 (my understanding is the certificate is valid from 2020 until 2028) at which point you can expect Apple to send you another certificate before it expires.
