### ISSUE TITLE
GetEllipticCurveAlgorithm function throws error

### ISSUE THREAD

**Issue by omerguvenis** [andrei-m-code/net-core-push-notifications#54]
Hello,

On "GetEllipticCurveAlgorithm" function of "AppleCryptoHelper", it gives error at "ECDsa.Create" call:

**The specified key parameters are not valid. Q.X and Q.Y are required fields. Q.X, Q.Y must be the same length. If D is specified it must be the same length as Q.X and Q.Y for named curves or the same length as Order for explicit curves.**

Lengths of
 keyParams.D.ToByteArrayUnsigned()
 q.XCoord.GetEncoded()
 q.YCoord.GetEncoded()
are
 31, 32 and 32 respectively.

I've filled all 
 AppBundleIdentifier
 P8PrivateKey
 P8PrivateKeyId
 ServerType
 TeamId
information corretly.

What may the be problem?

Regards,

**Comment by andrei-m-code** [comment]
Double check the certificate that you're passing in. It has to be an actual cert string, not a path or anything. Read the documentation carefully. The library works well, you just need to make sure everything is set up properly.
