### ISSUE TITLE
System.Security.Cryptography.ECParameters

### ISSUE THREAD

**Issue by Novotnde** [andrei-m-code/net-core-push-notifications#55]
Hello, 

I am having issues when calling the method SendAsync, I get the exception bellow. The method gets called but I have no response, can you advice please? 

We have  `  <TargetFrameworkVersion>v4.6.2</TargetFrameworkVersion>`

using the service 
```
 var sender = new ApnSender(_settings, _httpClient);
var status = await sender.SendAsync(ReturnMsgInJObject(pushMessage), deviceToken);
```
This is the exception I get when I am debugging - tried to upgrade version of .net framework to 4.8 and it didnt help 

```
System.TypeLoadException: Could not resolve type with token 01000016 from typeref (expected class 'System.Security.Cryptography.ECParameters' in assembly 'netstandard, Version=2.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51')
  at CorePush.Apple.ApnSender.CreateJwtToken () [0x0008a] in <42ebfc7367d540908a427353c242a75a>:0 
  at CorePush.Apple.ApnSender.<GetJwtToken>b__8_0 (System.String _) [0x00000] in <42ebfc7367d540908a427353c242a75a>:0 
  at System.Collections.Concurrent.ConcurrentDictionary`2[TKey,TValue].GetOrAdd (TKey key, System.Func`2[T,TResult] valueFactory) [0x00034] in /Users/builder/jenkins/workspace/build-package-osx-mono/2020-02/external/bockbuild/builds/mono-x64/external/corefx/src/System.Collections.Concurrent/src/System/Collections/Concurrent/ConcurrentDictionary.cs:1002 
  at CorePush.Apple.ApnSender.GetJwtToken () [0x00010] in <42ebfc7367d540908a427353c242a75a>:0 
  at CorePush.Apple.ApnSender.SendAsync (System.Object notification, System.String deviceToken, System.String apnsId, System.Int32 apnsExpiration, System.Int32 apnsPriority, System.Boolean isBackground, System.Threading.CancellationToken cancellationToken) [0x00086] in <42ebfc7367d540908a427353c242a75a>:0 
```

Please, let me know if you need anything else. 
Have a nice day

**Comment by andrei-m-code** [comment]
@Novotnde what environment are you running on? Is it your local or cloud? Windows, Linux or Mac?

**Comment by Novotnde** [comment]
Thank you for fast reply, local and Mac

**Comment by andrei-m-code** [comment]
@Novotnde yw! Everything seems to work well on my mac. Also It's weird that you're saying you can run .net 4.6.2 on your mac. It's not a cross-platform version of .net. I think you need to check the certificate that you're using. The library code may throw all sorts of different crypto related errors when the settings are incorrect.

**Comment by Novotnde** [comment]
Yes, we are targeting .net framework but running on  mono version Mono version 6.12.0.113. Ok, I will check that :) thank you for support.

**Comment by andrei-m-code** [comment]
oh wow. @Novotnde I wouldn't be surprised if mono is a problem. Try building a small "tester" project and target .net core 2.0+. See what happens. Let me know!

**Comment by Novotnde** [comment]
Hello, sorry for late response, yes, .net core test seems to be working better, got an error - Bad device id, but that's something more related.

**Comment by Novotnde** [comment]
@andrei-m-code Hey, I got a question related to .net framework. Since you have mentioned it worked in this I will just ask here rather then starting new issue. I have tried my .net framework app on windows but actually got and HHTP exception so I just been wondering if you have working .net framework app maybe you know the solution to this ? 

v System.Net.HttpWebRequest.set_ProtocolVersion(Version value)
   v System.Net.Http.HttpClientHandler.CreateAndPrepareWebRequest(HttpRequestMessage request)
   v System.Net.Http.HttpClientHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   v System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   v System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   v CorePush.Apple.ApnSender.<SendAsync>d__7.MoveNext()
   v System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   v System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   v System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   v workConsole.ApTest.<PushMessage>d__4.MoveNext() v souboru

**Comment by andrei-m-code** [comment]
what kind of http error?

**Comment by andrei-m-code** [comment]
it could be a lot of things. Would be interesting to know the status and the response body. Check exception message. Maybe it has something. In some cases you need to disable certificate validation and/or other things. This is why we allow to inject HttpClient rather than creating it within the sender class.

**Comment by Novotnde** [comment]
HTTP 1 or hhtp1.1 is allowed only

**Comment by reeceengle** [comment]
@andrei-m-code  - I'm running into the same exception here I was wondering if you might have anymore insight into this issue

I'm using WinHttpHandler v5.0.0 to create my HttpClient as follows:
`
            using (var http = new HttpClient(new Http2CustomHandler()))
            {
                var apn = new ApnSender(settings, http);
                Task.Run(() => apn.SendAsync(fullApnsPayload, notification.Device.DevicePushId)).Wait();
            }
`
My Http2CustomHandler is a simple override of WinHttpHandler:
`    
    public class Http2CustomHandler : WinHttpHandler
    {
        protected override Task<HttpResponseMessage> SendAsync(HttpRequestMessage request, System.Threading.CancellationToken cancellationToken)
        {
            request.Version = new Version("2.0");
            return base.SendAsync(request, cancellationToken);
        }
    }
`

Exception: 
`
{"Could not load type 'System.Security.Cryptography.ECParameters' from assembly 'netstandard, Version=2.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'.":"System.Security.Cryptography.ECParameters"}
`

Stack-Trace:
`   
at CorePush.Utils.AppleCryptoHelper.GetEllipticCurveAlgorithm(String privateKey)\r\n   at CorePush.Apple.ApnSender.CreateJwtToken()\r\n   at CorePush.Apple.ApnSender.<GetJwtToken>b__8_0(String _)\r\n   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory) in f:\\dd\\ndp\\clr\\src\\BCL\\system\\Collections\\Concurrent\\ConcurrentDictionary.cs:line 1070\r\n   at CorePush.Apple.ApnSender.GetJwtToken()\r\n   at CorePush.Apple.ApnSender.<SendAsync>d__7.MoveNext()
`

**Comment by igobl** [comment]
Same issue here using System.Net.HttpClient. If anyone managed to find a fix it would be very welcome given that binary protocol is being retired by Apple at the end of the month :| 

WebApp targeting .NET framework 4.6.2
CorePush v 3.0.4

`
var apnSettings = new ApnSettings()
{
// My settings here
};
var sender = new ApnSender(apnSettings, _httpClient);
var response = await sender.SendAsync(apnPayload, deviceToken: apnToken);
`

Stack-Trace:
Uncaught (non-HTTP) exception System.TypeLoadException: Could not load type 'System.Security.Cryptography.ECParameters' from assembly 'netstandard, Version=2.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'.
   at CorePush.Utils.AppleCryptoHelper.GetEllipticCurveAlgorithm(String privateKey)
   at CorePush.Apple.ApnSender.CreateJwtToken()
   at CorePush.Apple.ApnSender.<GetJwtToken>b__8_0(String _)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at CorePush.Apple.ApnSender.GetJwtToken()
   at CorePush.Apple.ApnSender.<SendAsync>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()

**Comment by andrei-m-code** [comment]
Thank you for all your feedback! It is working well with .NET 3.1+ (.NET Standard 2.1). But I'll try with .NET Standard 2.0 and see what happens.

**Comment by igobl** [comment]
I'll be trying some things as well, I'll update if I find anything.

**Comment by reeceengle** [comment]
@igobl @andrei-m-code  - This looks like a .NET 4.6.x issue -- ECParameters is only supported for .NET Framework 4.7+ 

https://docs.microsoft.com/en-us/dotnet/api/system.security.cryptography.ecparameters?view=net-5.0

**Comment by andrei-m-code** [comment]
@reeceengle I have no windows to testing on 4.6.x. If anyone else can - I'd appreciate it. Other than that all the .net core versions seem to work fine..

**Comment by reeceengle** [comment]
@andrei-m-code - 

I had to change my approach from using this library due to this dependency.  However, to get around using ECParameters in 4.6.x you can use:          
`var key = CngKey.Import(Convert.FromBase64String(certContent), CngKeyBlobFormat.Pkcs8PrivateBlob);`

However, that being said there are challenges using this here with IIS as you need to change AppPool settings.  This is not recommended for all .NET Framework projects, just 4.6.x as a workaround.

**Comment by nextgenerationtr** [comment]
I did a fair amount of search on the net, but could not figure out a solution.
I use .Net Framework 4.7.2.

I get the following exception right after executing following statements:

`var apn = new ApnSender(settings, http);
var payload = new AppleNotificationHttp2(Guid.NewGuid(), message, title);`

Exception details:
`InnerException: System.Net.Http.WinHttpException (0x80072F8F): Error 12175 calling WINHTTP_CALLBACK_STATUS_REQUEST_ERROR, 'A security error occurred'. at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() at System.Threading.Tasks.RendezvousAwaitable`1.GetResult() at System.Net.Http.WinHttpHandler.d__109.MoveNext()
StackTrace: at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at CorePush.Apple.ApnSender.d__7.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() at PushApple.d__7.MoveNext()`

**Comment by andrei-m-code** [comment]
One thing to try:

        services.AddHttpClient<IApnSenderFactory, ApnSenderFactory>().ConfigurePrimaryHttpMessageHandler(() =>
        {
            var handler = new HttpClientHandler();
            handler.ServerCertificateCustomValidationCallback = HttpClientHandler.DangerousAcceptAnyServerCertificateValidator;
            return handler;
        });
