### ISSUE TITLE
have two issue 

### ISSUE THREAD

**Issue by explosoft** [andrei-m-code/net-core-push-notifications#57]
1.)The input is not a valid Base-64 string as it contains a non-base 64 character, more than two padding characters, or an illegal character among the padding characters

2.)P8 private key  - have general p8 file , how to insert on asp core ?

**Comment by andrei-m-code** [comment]
1) Not sure what you mean by that. Please elaborate.
2) You need to pass the contents of that file as a p8privateKey parameter.

Please carefully read the documentation. Good luck
