### ISSUE TITLE
Where is fcmReceiverToken

### ISSUE THREAD

**Issue by landnd** [andrei-m-code/net-core-push-notifications#60]
To send notification to android device, where do I get fcmReceiverToken?
Also, is there any way to just use one code part to send notification to both iOS and Android?

**Comment by andrei-m-code** [comment]
@landnd 

1. FCM receiver must be the device token. You have to subscribe your device, get the token and use it on your server side to send notification to the device.
2. You can use FCM sender for Android, WebPush and iOS. However they all have different payloads and iOS push requires substantial setup on the Firebase side. Maybe this can help: https://firebase.google.com/docs/cloud-messaging/ios/client
