### ISSUE TITLE
Push icon

### ISSUE THREAD

**Issue by dennisc2** [andrei-m-code/net-core-push-notifications#64]
Wanted to check if it allow to add icon for the push message? Which can display in mobile device message with icon?

**Comment by andrei-m-code** [comment]
@dennisc2 you can do it if it’s allowed by the platform. Are you talking about web android or ios? The lib allows you to send any payload but you need to follow the official document to send exactly what’s expected on the other end.

**Comment by dennisc2** [comment]
Sorry for the newbie question, but do I add that to the payload object? Would you have any sample of it? Would like to send to both android and iOS, which should support the icon for android cloud message?

**Comment by andrei-m-code** [comment]
please refer to the official documentation. I can't really help with it, sorry
