### ISSUE TITLE
Only HTTP/1.0 and HTTP/1.1 version requests are currently supported

### ISSUE THREAD

**Issue by jlangedk** [andrei-m-code/net-core-push-notifications#69]
I have installed the nuget package in my .net framework 4.7.2 backend and gets this response Only HTTP/1.0 and HTTP/1.1 version requests are currently supported, when calling apn.SendAsync. I can see in your code that you set the http request message version to 2: message.Version = new Version(2, 0); What can I do to fix my problem ? B.r. Jan Lange

**Comment by andrei-m-code** [comment]
This might've been a requirement from Apple, it has to be 2.0..
