### ISSUE TITLE
Sending push notifications in batches?

### ISSUE THREAD

**Issue by pvhd** [andrei-m-code/net-core-push-notifications#7]
From the guideline, I didn't see how to send multiple push notifications at a time. Could you please show me how to do that? Thank you.

**Comment by andrei-m-code** [comment]
@pvhd currently you can only do it in a foreach loop e.g.:
```
using (var fcm = new FcmSender(serverKey, senderId))
{
    var receivers = await GetReceiversAsync();
    var tasks = receivers.Select(receiver => fcm.SendAsync(...));
    await Task.WhenAll(tasks);
}
```
Please note, if you have receivers from both platforms (Apple and Google FCM) you'd need 2 different senders.
