### ISSUE TITLE
ApnsResponse from ApnSender.Send has IsSuccess = true, but I never receive notification?

### ISSUE THREAD

**Issue by redbird19** [andrei-m-code/net-core-push-notifications#71]
It seems like I did everything correct.  No error is thrown, ApnsResponse.Error = null, and ApnsResponse.IsSuccess = true, but no notification is ever delivered.  I'm not sure what else I can look at to figure out why the notification isn't sent, any ideas?

**Comment by redbird19** [comment]
Nevermind, I got it to work.  The problem was with my payload having a slight deviation from the spec.  Once I fixed that, it worked like a charm!

**Comment by dsouzajoel** [comment]
Hi redbird19 - what did you change in the payload to get it to work? I'm having the same issue. Thanks.

Payload

{"aps":{"alert":{"title":"Checking out Kelly Lola Local","body":"Appointment Created: Kelly Lola on Thu, Jul 16 @ 6:15 pm"}}}
