### ISSUE TITLE
Support for System.Text.JSON

### ISSUE THREAD

**Issue by sebastienlabine** [andrei-m-code/net-core-push-notifications#74]
When can we expect support for System.Text.JSON?

https://github.com/andrei-m-code/net-core-push-notifications/pull/59#issuecomment-916141433

**Comment by andrei-m-code** [comment]
That has to be a version 4 with ability to swap serializers. I'll do it sometime in Jan

**Comment by egenita** [comment]
Any update for migrating to System.Text.JSON?

**Comment by andrei-m-code** [comment]
@egenita working on it. sorry for the delay

**Comment by andrei-m-code** [comment]
@egenita I have a PR ready but for v4.0.0 I'd like to migrate to FCM HTTP v1 too, so stay tuned I'll get that done hopefully soon.
https://github.com/andrei-m-code/net-core-push-notifications/pull/77

**Comment by andrei-m-code** [comment]
Implemented in v4.0.0
