### ISSUE TITLE
Usage clarification

### ISSUE THREAD

**Issue by co-dax** [andrei-m-code/net-core-push-notifications#81]
I am still using version 3.x and I am about to migrate to version 4.x.

Can we still send push notificaitons to iOS through Firebase as we could with version 3.x or should we take additional steps for that.

At the following link [https://github.com/andrei-m-code/net-core-push-notifications#firebase-cloud-messages-for-android-ios-and-web](https://github.com/andrei-m-code/net-core-push-notifications#firebase-cloud-messages-for-android-ios-and-web) it is saying `**Firebase Cloud Messages** for Android, **iOS** and Web...` while here [https://github.com/andrei-m-code/net-core-push-notifications#firebase-ios-notifications](https://github.com/andrei-m-code/net-core-push-notifications#firebase-ios-notifications) it is saying `Firebase iOS notifications...**If you want to use Firebase to send iOS notifications**, please checkout this article:...`

In the paragraph above in the first part it seems to be conveying that the library is sending **Firebase** cloud messages to **iOS** but then at the same url it is saying **If you want to use Firebase to send iOS notifications...**

Essentially, is it enough do the following from [this link](https://github.com/andrei-m-code/net-core-push-notifications#firebase-cloud-messages-for-android-ios-and-web) to send push notifications to iOS (as far as my backend server is concerned):
`var firebaseSettingsJson = await File.ReadAllTextAsync('./link/to/my-project-123345-e12345.json');
var fcm = new FirebaseSender(firebaseSettingsJson, httpClient);
await fcm.SendAsync(payload);` ?

Thanks!

**Comment by andrei-m-code** [comment]
Hi @co-dax yes you can still send the notifications to apple devices using Firebase. You just need to be sure the payload is migrated to the new version. For that it's better to have a look at firebase documentation.
