### ISSUE TITLE
For Anyone Who Has Issues with Azure Service & Firebase (Cryptography) - See this...

### ISSUE THREAD

**Issue by Thomr77** [andrei-m-code/net-core-push-notifications#82]
Anyone who has issues sending via Firebase using an Azure Service (cryptography - file not found). Follow the steps here:
https://stackoverflow.com/questions/66367406/cngkey-system-security-cryptography-cryptographicexception-the-system-cannot-fin

**Comment by andrei-m-code** [comment]
Excellent point. I'll add it to readme
