### ISSUE TITLE
FirebaseSettings are a record thus not allowing binding to appsettings.json

### ISSUE THREAD

**Issue by t00** [andrei-m-code/net-core-push-notifications#86]
I am upgrading from v3.x and since a few years of using the library, we had a code to automatically configure settings from appsettings.json:

```
            services.Configure<ApnSettings>(configuration.GetSection("ApnSettings"));
            services.Configure<FirebaseSettings>(configuration.GetSection("FcmSettings"));
```

FirebaseSettings is no longer working using this method as "FirebaseSettings does not have a parameterless constructor". ApnSettings on the other hand works fine still.

Could you please change FirebaseSettings back to class and for compatibility create 2 constructors?

**Comment by andrei-m-code** [comment]
Hi @t00 

I suggest you don't use FirebaseSettings. Instead put the contents of that firebase service account key json file in your env settings and read it to create FirebaseSender.

```
var serviceAccountJsonContents = GetItFromYourPreferredSettingsLocation();
services.AddHttpClient<FirebaseSender>(http => new FirebaseSender(serviceAccountJsonContents, http));
```

With newer version of firebase APIs things are a bit more complicated unfortunately.
