### ISSUE TITLE
both alert and silent notifications ios13

### ISSUE THREAD

**Issue by asaadmirza** [andrei-m-code/net-core-push-notifications#9]
hi dear ,
with your code only i can send alert notification without background fetch content , kindly help me to solve this issue , even i set apns-push-type = background but i still not receive it , only receive alert when i change apns-push-type to alert but no silent push notification. my payload is 
{
   "aps" :  {
                "alert" :
                            {
                                "title" :"test",
                               "body" : "hellooooo",
                             
                            },
                            "badge" : 1,
                            "sound" : "default",
                            "content_available" : 1,
                        },
                        "person"
                        {
                            "userIdTo": 12,
                             "ListID" : 0,
                         
                        }
}

**Comment by Eternal21** [comment]
Try changing priority from 10 to 5.

**Comment by asaadmirza** [comment]
I tried it but still not update in background , I set apps-push-type to alert , just I receive the notification without update content in background , only when I open background app refresh from setting it work , but in iOS 12 no need to open this option from settings.

**Comment by Sthefanny** [comment]
Hi.

How can I send an Header to FcmSender? I don't know how to send apns-push-type or apns-priority

**Comment by andrei-m-code** [comment]
@Sthefanny please read the README. There are some notification model examples that might be helpful. For properties with dashes you can use attribute `[JsonProperty("apns-push-type")]` and it will be serialized accordingly.
